INSERT INTO USERS (USERNAME, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, PASSWORD)
  VALUES ('beca', 'Adrian', 'Marcelo', 'Paredes', 'adrianp@epidataconsulting.com',
  '$2a$10$HK0EYADmdoOFg9vW6DGEG.He1G4ogsMwyJ2vY/zQuWgPnH2VNBfBC');
  
INSERT INTO DEVELOPERS (NAME, LAST_NAME, SENIORITY)
  VALUES ('Adrian', 'Paredes', 2);
INSERT INTO DEVELOPERS (NAME, LAST_NAME, SENIORITY)
  VALUES ('German', 'Hohmann', 2);
INSERT INTO DEVELOPERS (NAME, LAST_NAME, SENIORITY)
  VALUES ('Pablo', 'Blauer', 2);
  
INSERT INTO ROLES (NAME) 
  VALUES ('Admin');
  
INSERT INTO PERMISSIONS (NAME)
  VALUES ('READ_DEVELOPER');
INSERT INTO PERMISSIONS (NAME)
  VALUES ('CREATE_DEVELOPER');
INSERT INTO PERMISSIONS (NAME)
  VALUES ('UPDATE_DEVELOPER');
INSERT INTO PERMISSIONS (NAME)
  VALUES ('DELETE_DEVELOPER');
INSERT INTO PERMISSIONS (NAME)
  VALUES ('CREATE_ROLE');

  
INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
  VALUES (1,1);
  
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 1);
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 2);
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 3);
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 4);
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 5);