
CREATE TABLE USERS
(
  ID bigserial UNIQUE,
  USERNAME character varying(255) NOT NULL,
  FIRST_NAME character varying(255) NOT NULL,
  MIDDLE_NAME character varying(255) NULL,
  LAST_NAME character varying(255) NOT NULL,
  EMAIL character varying(255) NOT NULL,
  PASSWORD character varying(255) NOT NULL,
  CONSTRAINT USERS_PKEY PRIMARY KEY (ID)
);

CREATE TABLE DEVELOPERS
(
  ID bigserial UNIQUE,
  NAME character varying(255) NOT NULL,
  LAST_NAME character varying(255) NOT NULL,
  SENIORITY INTEGER,
  DATE_ENTRY DATE,
  CONSTRAINT DEV_PKEY PRIMARY KEY (ID)
);

CREATE TABLE ROLES
(
  ID bigserial NOT NULL,
  NAME character varying(255) NOT NULL,
  CONSTRAINT ROLES_PKEY PRIMARY KEY (ID)
);

CREATE TABLE PERMISSIONS
(
  ID bigserial NOT NULL,
  NAME character varying(255) NOT NULL,
  CONSTRAINT PERM_PKEY PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLES
(
  USER_ID bigint NOT NULL,
  ROLE_ID bigint NOT NULL,
  CONSTRAINT UR_PKEY PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT UR_ROLE_FKEY FOREIGN KEY (ROLE_ID)
      REFERENCES ROLES (ID)
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT UR_USER_FKEY FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID)
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE ROLES_PERMISSIONS
(
  ROLE_ID bigint NOT NULL,
  PERMISSION_ID bigint NOT NULL,
  CONSTRAINT RP_PKEY PRIMARY KEY (ROLE_ID, PERMISSION_ID),
  CONSTRAINT RP_PERM_FKEY FOREIGN KEY (PERMISSION_ID)
      REFERENCES PERMISSIONS (ID)
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT RP_ROLE_ID_FKEY FOREIGN KEY (ROLE_ID)
      REFERENCES ROLES (ID)
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
