INSERT INTO USERS (USERNAME, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, PASSWORD)
  VALUES ('admin', 'Adrian', 'Marcelo', 'Paredes', 'adrianp@epidataconsulting.com',
  '$2a$10$HK0EYADmdoOFg9vW6DGEG.He1G4ogsMwyJ2vY/zQuWgPnH2VNBfBC');
  
INSERT INTO USERS (USERNAME, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, PASSWORD)
  VALUES ('beca', 'Bago', 'Test', 'Epidata', 'bago@epidataconsulting.com',
  '$2a$10$HK0EYADmdoOFg9vW6DGEG.He1G4ogsMwyJ2vY/zQuWgPnH2VNBfBC');

INSERT INTO DEVELOPERS (NAME, LAST_NAME, SENIORITY)
  VALUES ('Adrian', 'Paredes', 2);
INSERT INTO DEVELOPERS (NAME, LAST_NAME, SENIORITY)
  VALUES ('German', 'Hohmann', 2);
INSERT INTO DEVELOPERS (NAME, LAST_NAME, SENIORITY)
  VALUES ('Pablo', 'Blauer', 2);
  
INSERT INTO ROLES (ID, NAME) 
  VALUES (1, 'Admin');
  
INSERT INTO PERMISSIONS (ID, NAME)
  VALUES (1,'READ_DEVELOPER');
INSERT INTO PERMISSIONS (ID, NAME)
  VALUES (2,'CREATE_DEVELOPER');
INSERT INTO PERMISSIONS (ID, NAME)
  VALUES (3,'UPDATE_DEVELOPER');
INSERT INTO PERMISSIONS (ID, NAME)
  VALUES (4,'DELETE_DEVELOPER');
  
INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
  VALUES (1,1);
  
INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
  VALUES (21,1);

INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 1);
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 2);
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 3);
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
  VALUES (1, 4);